// Types constant for redux actions
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_INITIAL_POSTS = 'SET_INITIAL_POSTS';
export const INJECT_POSTS_TO_NEWSFEED = 'INJECT_POSTS_TO_NEWSFEED';
export const REVEAL_COLLECTED_POSTS = 'REVEAL_COLLECTED_POSTS';
export const ADD_COMMENT_TO_INITIAL_POSTS = 'ADD_COMMENT_TO_INITIAL_POSTS';
export const FETCH_SEARCH_RESULT = 'FETCH_SEARCH_RESULT';
export const RESET_SEARCH_STATE = 'RESET_SEARCH_STATE';
export const GET_USER_INFORMATION = 'GET_USER_INFORMATION';
export const SET_NOTIFICATION_STATE = 'SET_NOTIFICATION_STATE';
export const SET_SOCKET_STATUS = 'SET_SOCKET_STATUS';
export const UPDATE_UNREAD_NOTIFICATIONS = 'UPDATE_UNREAD_NOTIFICATIONS';
export const RESET_REDUX_STATE = 'RESET_REDUX_STATE';
export const RESET_UNREAD_NOTIFICATION = 'RESET_UNREAD_NOTIFICATION';
export const SET_PROFILE_DATA = 'SET_PROFILE_DATA';
